
export const ARABIC_FONTS = [
  { name: 'Cairo', family: "'Cairo', sans-serif" },
  { name: 'Almarai', family: "'Almarai', sans-serif" },
  { name: 'Tajawal', family: "'Tajawal', sans-serif" },
  { name: 'Amiri', family: "'Amiri', serif" },
  { name: 'Changa', family: "'Changa', sans-serif" },
  { name: 'Lateef', family: "'Lateef', cursive" },
  { name: 'Reem Kufi', family: "'Reem Kufi', sans-serif" },
  { name: 'Aref Ruqaa', family: "'Aref Ruqaa', serif" },
  { name: 'Lemonada', family: "'Lemonada', cursive" },
  { name: 'Mirza', family: "'Mirza', serif" },
  { name: 'Markazi Text', family: "'Markazi Text', serif" },
  { name: 'Mada', family: "'Mada', sans-serif" },
  { name: 'Jomhuria', family: "'Jomhuria', cursive" },
  { name: 'Lalezar', family: "'Lalezar', cursive" },
  { name: 'Katibeh', family: "'Katibeh', cursive" },
  { name: 'Harmattan', family: "'Harmattan', sans-serif" },
  { name: 'Scheherazade New', family: "'Scheherazade New', serif" },
  { name: 'Kufam', family: "'Kufam', sans-serif" },
  { name: 'Qahiri', family: "'Qahiri', cursive" },
  { name: 'Baloo Bhaijaan 2', family: "'Baloo Bhaijaan 2', cursive" },
  { name: 'IBM Plex Sans Arabic', family: "'IBM Plex Sans Arabic', sans-serif" },
  { name: 'Noto Sans Arabic', family: "'Noto Sans Arabic', sans-serif" },
  { name: 'Readex Pro', family: "'Readex Pro', sans-serif" },
  { name: 'El Messiri', family: "'El Messiri', sans-serif" },
  { name: 'Rakkas', family: "'Rakkas', cursive" },
  { name: 'Vibes', family: "'Vibes', cursive" },
  { name: 'Beiruti', family: "'Beiruti', sans-serif" },
  { name: 'Zain', family: "'Zain', sans-serif" },
  { name: 'Madani', family: "'Madani Custom', sans-serif" },
  { name: 'Sakkal Majalla', family: "'Sakkal Majalla', sans-serif" },
  { name: 'Traditional Arabic', family: "'Traditional Arabic', serif" },
  { name: 'Simplified Arabic', family: "'Simplified Arabic', sans-serif" },
  { name: 'Andalus', family: "'Andalus', serif" },
  { name: 'Kufi Standard', family: "'Kufi Standard', sans-serif" },
  { name: 'DecoType Thuluth', family: "'DecoType Thuluth', cursive" },
  { name: 'Noto Naskh Arabic', family: "'Noto Naskh Arabic', serif" },
  { name: 'Noto Kufi Arabic', family: "'Noto Kufi Arabic', sans-serif" },
  { name: 'Noto Sans Arabic UI', family: "'Noto Sans Arabic UI', sans-serif" },
  { name: 'Alexandria', family: "'Alexandria', sans-serif" },
  { name: 'Granada', family: "'Granada', serif" },
  { name: 'Baghdad', family: "'Baghdad', sans-serif" },
  { name: 'KacstTitleL', family: "'KacstTitleL', sans-serif" },
  { name: 'KacstOne', family: "'KacstOne', sans-serif" },
  { name: 'KacstDigital', family: "'KacstDigital', monospace" },
  { name: 'KacstFarsi', family: "'KacstFarsi', serif" },
  { name: 'KacstBook', family: "'KacstBook', serif" },
  { name: 'KacstLetter', family: "'KacstLetter', serif" },
  { name: 'KacstPoster', family: "'KacstPoster', sans-serif" },
  { name: 'KacstQurn', family: "'KacstQurn', serif" },
  { name: 'KacstArt', family: "'KacstArt', sans-serif" }
];

export const ENGLISH_FONTS = [
  { name: 'Inter', family: "'Inter', sans-serif" },
  { name: 'Roboto', family: "'Roboto', sans-serif" },
  { name: 'Montserrat', family: "'Montserrat', sans-serif" },
  { name: 'Playfair Display', family: "'Playfair Display', serif" },
  { name: 'Poppins', family: "'Poppins', sans-serif" },
  { name: 'Outfit', family: "'Outfit', sans-serif" },
  { name: 'Libre Baskerville', family: "'Libre Baskerville', serif" },
  { name: 'Dancing Script', family: "'Dancing Script', cursive" },
  { name: 'Open Sans', family: "'Open Sans', sans-serif" },
  { name: 'Lato', family: "'Lato', sans-serif" },
  { name: 'Oswald', family: "'Oswald', sans-serif" },
  { name: 'Raleway', family: "'Raleway', sans-serif" },
  { name: 'Merriweather', family: "'Merriweather', serif" },
  { name: 'Noto Sans', family: "'Noto Sans', sans-serif" },
  { name: 'Nunito', family: "'Nunito', sans-serif" },
  { name: 'Rubik', family: "'Rubik', sans-serif" },
  { name: 'Ubuntu', family: "'Ubuntu', sans-serif" },
  { name: 'Lora', family: "'Lora', serif" },
  { name: 'Quicksand', family: "'Quicksand', sans-serif" },
  { name: 'Kanit', family: "'Kanit', sans-serif" },
  { name: 'Titillium Web', family: "'Titillium Web', sans-serif" },
  { name: 'Josefin Sans', family: "'Josefin Sans', sans-serif" },
  { name: 'Source Sans Pro', family: "'Source Sans Pro', sans-serif" },
  { name: 'Arvo', family: "'Arvo', serif" },
  { name: 'Dosis', family: "'Dosis', sans-serif" },
  { name: 'Oxygen', family: "'Oxygen', sans-serif" },
  { name: 'Anton', family: "'Anton', sans-serif" },
  { name: 'Lobster', family: "'Lobster', cursive" },
  { name: 'Pacifico', family: "'Pacifico', cursive" },
  { name: 'Shadows Into Light', family: "'Shadows Into Light', cursive" },
  { name: 'Indie Flower', family: "'Indie Flower', cursive" },
  { name: 'Caveat', family: "'Caveat', cursive" },
  { name: 'Amatic SC', family: "'Amatic SC', cursive" },
  { name: 'Courgette', family: "'Courgette', cursive" },
  { name: 'Great Vibes', family: "'Great Vibes', cursive" },
  { name: 'Kaushan Script', family: "'Kaushan Script', cursive" },
  { name: 'Satisfy', family: "'Satisfy', cursive" },
  { name: 'Cookie', family: "'Cookie', cursive" },
  { name: 'Sacramento', family: "'Sacramento', cursive" },
  { name: 'Parisienne', family: "'Parisienne', cursive" },
  { name: 'Yellowtail', family: "'Yellowtail', cursive" },
  { name: 'Berkshire Swash', family: "'Berkshire Swash', cursive" },
  { name: 'Allura', family: "'Allura', cursive" },
  { name: 'Bebas Neue', family: "'Bebas Neue', sans-serif" },
  { name: 'Abril Fatface', family: "'Abril Fatface', cursive" },
  { name: 'Cinzel', family: "'Cinzel', serif" },
  { name: 'Exo 2', family: "'Exo 2', sans-serif" },
  { name: 'Fira Sans', family: "'Fira Sans', sans-serif" },
  { name: 'Inconsolata', family: "'Inconsolata', monospace" },
  { name: 'Marck Script', family: "'Marck Script', cursive" }
];
