import { ThemeConfig } from './types';

export const THEMES: ThemeConfig[] = [
  {
    id: 'qaaf-classic',
    name: 'قاف الكلاسيكي (الافتراضي)',
    description: 'التصميم الأصلي لبراند قاف، يجمع بين الفخامة والبساطة.',
    primaryColor: '#92400e',
    secondaryColor: '#fdf8f4',
    fontFamily: 'Cairo',
    borderRadius: 'lg',
    headerStyle: 'transparent',
    cardStyle: 'classic',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard',
    heroTitle: 'أناقة تتحدث عنك | أزياء QAAF الحصرية',
    heroSubtitle: 'اكتشفي تشكيلتنا الفاخرة لعام 2026 المصنوعة يدوياً من أجود خامات القطن المصري والكتان الطبيعي لتناسب ذوقك الرفيع.',
    aboutTitle: 'حكاية QAAF للأزياء الفاخرة',
    aboutDescription: 'قاف (QAAF) ليست مجرد علامة تجارية للملابس، بل هي رؤية مصرية تجمع بين الفخامة المعاصرة والأصالة. نحن نؤمن بأن ملابسك هي مرآة لشخصيتك، لذا نحرص على استخدام أفضل الأقمشة والقطن الطبيعي وتصميم قطع حصرية تمنحك الثقة والأناقة في كل مناسبة. كل قطعة صُممت وصُنعت بشغف وحب لتكون جزءاً من قصتك وتدوم معكِ للأبد.'
  },
  {
    id: 'minimal-white',
    name: 'الأبيض البسيط (Minimal)',
    description: 'تصميم هادئ ونظيف يركز على المنتجات بشكل أساسي.',
    primaryColor: '#171717',
    secondaryColor: '#ffffff',
    fontFamily: 'Inter',
    borderRadius: 'none',
    headerStyle: 'minimal',
    cardStyle: 'minimal',
    heroLayout: 'minimal',
    productGridLayout: 'compact',
    aboutLayout: 'minimal',
    productDetailLayout: 'stacked',
    heroTitle: 'بساطة التصميم، رقي الإطلالة',
    heroSubtitle: 'نركز على ما يهم حقاً: ملاءمة مثالية، خامات طبيعية، وتفاصيل تصنع الفارق.',
    aboutTitle: 'فلسفة البساطة والأناقة',
    aboutDescription: 'في عالم مليء بالتعقيد، نختار البساطة. أزياءنا مصممة لتكون مريحة، متينة، وسهلة التنسيق لتناسب نمط حياتك اليومي.'
  },
  {
    id: 'luxury-gold',
    name: 'الذهبي الفاخر (Luxury)',
    description: 'مستوحى من أرقى دور التجميل العالمية، بلمسات ذهبية.',
    primaryColor: '#b45309',
    secondaryColor: '#000000',
    fontFamily: 'Playfair Display',
    borderRadius: 'md',
    headerStyle: 'solid',
    cardStyle: 'modern',
    heroLayout: 'split',
    productGridLayout: 'standard',
    aboutLayout: 'reversed',
    productDetailLayout: 'reversed',
    heroTitle: 'فخامة التفاصيل وإرث الأناقة',
    heroSubtitle: 'تجربة أزياء ملكية تليق بجمالك الخاص، بتصاميم حصرية وأرقى خامات الحرير والكشمير.',
    aboutTitle: 'إرث الأزياء الراقية',
    aboutDescription: 'نستحضر أسرار الخياطة الفاخرة لنقدم لكِ تصاميم كلاسيكية خالدة تجعلكِ محط الأنظار في كل محفل.'
  },
  {
    id: 'nature-green',
    name: 'الطبيعة الخضراء (Nature)',
    description: 'تصميم يعكس الأزياء المستدامة والأقمشة العضوية الصديقة للبيئة.',
    primaryColor: '#166534',
    secondaryColor: '#f0fdf4',
    fontFamily: 'Cairo',
    borderRadius: 'full',
    headerStyle: 'transparent',
    cardStyle: 'classic',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'modern-bold',
    name: 'العصري الجريء (Bold)',
    description: 'تصميم قوي وجذاب بتباين عالي وألوان واضحة.',
    primaryColor: '#be123c',
    secondaryColor: '#fff1f2',
    fontFamily: 'Cairo',
    borderRadius: 'none',
    headerStyle: 'solid',
    cardStyle: 'bold',
    heroLayout: 'magazine',
    productGridLayout: 'masonry',
    aboutLayout: 'reversed',
    productDetailLayout: 'standard'
  },
  {
    id: 'soft-pink',
    name: 'الوردي الناعم (Soft)',
    description: 'تصميم رقيق ومريح للعين، مثالي لأزياء الأطفال والملابس المنزلية الناعمة.',
    primaryColor: '#db2777',
    secondaryColor: '#fdf2f8',
    fontFamily: 'Cairo',
    borderRadius: 'lg',
    headerStyle: 'transparent',
    cardStyle: 'modern',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'dark-mode',
    name: 'الوضع الليلي (Dark)',
    description: 'تصميم غامق وعصري يقلل من إجهاد العين.',
    primaryColor: '#fbbf24',
    secondaryColor: '#0f172a',
    fontFamily: 'Cairo',
    borderRadius: 'md',
    headerStyle: 'solid',
    cardStyle: 'modern',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'editorial-serif',
    name: 'المجلة (Editorial)',
    description: 'تصميم يشبه مجلات الموضة العالمية بخطوط سيريف أنيقة.',
    primaryColor: '#000000',
    secondaryColor: '#fafaf9',
    fontFamily: 'Playfair Display',
    borderRadius: 'none',
    headerStyle: 'minimal',
    cardStyle: 'minimal',
    heroLayout: 'magazine',
    productGridLayout: 'masonry',
    aboutLayout: 'minimal',
    productDetailLayout: 'stacked'
  },
  {
    id: 'tech-clean',
    name: 'التقني النظيف (Tech)',
    description: 'تصميم مستوحى من شركات التكنولوجيا الحديثة، دقيق ومنظم.',
    primaryColor: '#2563eb',
    secondaryColor: '#f8fafc',
    fontFamily: 'Inter',
    borderRadius: 'sm',
    headerStyle: 'solid',
    cardStyle: 'modern',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'vintage-retro',
    name: 'فينتج (Vintage)',
    description: 'تصميم كلاسيكي يعود بنا إلى زمن الجمال الأصيل.',
    primaryColor: '#7c2d12',
    secondaryColor: '#fff7ed',
    fontFamily: 'Cairo',
    borderRadius: 'md',
    headerStyle: 'transparent',
    cardStyle: 'classic',
    heroLayout: 'split',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'ocean-breeze',
    name: 'نسيم المحيط (Ocean)',
    description: 'تصميم منعش بألوان البحر والسماء.',
    primaryColor: '#0369a1',
    secondaryColor: '#f0f9ff',
    fontFamily: 'Cairo',
    borderRadius: 'lg',
    headerStyle: 'transparent',
    cardStyle: 'modern',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'lavender-dream',
    name: 'حلم اللافندر (Lavender)',
    description: 'تصميم مهدئ بألوان اللافندر الرقيقة.',
    primaryColor: '#7e22ce',
    secondaryColor: '#faf5ff',
    fontFamily: 'Cairo',
    borderRadius: 'full',
    headerStyle: 'minimal',
    cardStyle: 'classic',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'sunset-glow',
    name: 'وهج الغروب (Sunset)',
    description: 'تصميم دافئ بألوان الغروب الساحرة.',
    primaryColor: '#ea580c',
    secondaryColor: '#fff7ed',
    fontFamily: 'Cairo',
    borderRadius: 'md',
    headerStyle: 'solid',
    cardStyle: 'bold',
    heroLayout: 'split',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'urban-street',
    name: 'ستريت ستايل (Urban)',
    description: 'تصميم شبابي وعصري مستوحى من ثقافة الشارع.',
    primaryColor: '#000000',
    secondaryColor: '#e5e7eb',
    fontFamily: 'Inter',
    borderRadius: 'none',
    headerStyle: 'minimal',
    cardStyle: 'bold',
    heroLayout: 'minimal',
    productGridLayout: 'compact',
    aboutLayout: 'minimal',
    productDetailLayout: 'stacked'
  },
  {
    id: 'royal-purple',
    name: 'الأرجواني الملكي (Royal)',
    description: 'تصميم فخم يعكس الرقي والتميز.',
    primaryColor: '#581c87',
    secondaryColor: '#f5f3ff',
    fontFamily: 'Playfair Display',
    borderRadius: 'lg',
    headerStyle: 'solid',
    cardStyle: 'modern',
    heroLayout: 'split',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'earthy-clay',
    name: 'ألوان الطين (Earthy)',
    description: 'تصميم مستوحى من ألوان الأرض الطبيعية.',
    primaryColor: '#9a3412',
    secondaryColor: '#fffaf0',
    fontFamily: 'Cairo',
    borderRadius: 'md',
    headerStyle: 'transparent',
    cardStyle: 'classic',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'midnight-blue',
    name: 'أزرق منتصف الليل (Midnight)',
    description: 'تصميم عميق وهادئ يوحي بالثقة والجودة.',
    primaryColor: '#1e3a8a',
    secondaryColor: '#eff6ff',
    fontFamily: 'Cairo',
    borderRadius: 'sm',
    headerStyle: 'solid',
    cardStyle: 'modern',
    heroLayout: 'split',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'candy-pop',
    name: 'كاندي بوب (Candy)',
    description: 'تصميم مبهج ومليء بالحيوية والألوان الزاهية.',
    primaryColor: '#f43f5e',
    secondaryColor: '#fff1f2',
    fontFamily: 'Cairo',
    borderRadius: 'full',
    headerStyle: 'transparent',
    cardStyle: 'modern',
    heroLayout: 'center',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  },
  {
    id: 'monochrome-gray',
    name: 'رمادي أحادي (Mono)',
    description: 'تصميم راقي يعتمد على تدرجات الرمادي والأسود.',
    primaryColor: '#374151',
    secondaryColor: '#f9fafb',
    fontFamily: 'Inter',
    borderRadius: 'none',
    headerStyle: 'minimal',
    cardStyle: 'minimal',
    heroLayout: 'minimal',
    productGridLayout: 'compact',
    aboutLayout: 'minimal',
    productDetailLayout: 'stacked'
  },
  {
    id: 'golden-sand',
    name: 'رمال ذهبية (Sand)',
    description: 'تصميم دافئ ومشرق مستوحى من رمال الصحراء الذهبية.',
    primaryColor: '#d97706',
    secondaryColor: '#fffbeb',
    fontFamily: 'Cairo',
    borderRadius: 'lg',
    headerStyle: 'transparent',
    cardStyle: 'classic',
    heroLayout: 'split',
    productGridLayout: 'standard',
    aboutLayout: 'standard',
    productDetailLayout: 'standard'
  }
];
